apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-applied-demo
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: ai-applied-demo-ui-configmap
    behavior: create
    literals:
      - API_PROXY=http://ai-applied-demo-ui-service:8080

generatorOptions:
  disableNameSuffixHash: true
